"Resource/UI/DropDownAntialias.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"156"
		"tall"					"205"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}
	
	"BtnAntialias0"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias0"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias9"
		"navDown"				"BtnAntialias1"
		"labelText"				"_antialias0"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias0"
		"OnlyActiveUser"		"1"
	}

	"BtnAntialias1"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias1"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias0"
		"navDown"				"BtnAntialias2"
		"labelText"				"_antialias1"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias1"
		"OnlyActiveUser"		"1"
	}
	
	"BtnAntialias2"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias2"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias1"
		"navDown"				"BtnAntialias3"
		"labelText"				"_antialias2"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias2"
		"OnlyActiveUser"		"1"
	}
	
	"BtnAntialias3"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias3"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias2"
		"navDown"				"BtnAntialias4"
		"labelText"				"_antialias3"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias3"
		"OnlyActiveUser"		"1"
	}
	
	"BtnAntialias4"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias4"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias3"
		"navDown"				"BtnAntialias5"
		"labelText"				"_antialias4"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias4"
		"OnlyActiveUser"		"1"
	}
	
	"BtnAntialias5"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias5"
		"xpos"					"0"
		"ypos"					"100"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias4"
		"navDown"				"BtnAntialias6"
		"labelText"				"_antialias5"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias5"
		"OnlyActiveUser"		"1"
	}
	
	"BtnAntialias6"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias6"
		"xpos"					"0"
		"ypos"					"120"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias5"
		"navDown"				"BtnAntialias7"
		"labelText"				"_antialias6"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias6"
		"OnlyActiveUser"		"1"
	}
	
	"BtnAntialias7"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias7"
		"xpos"					"0"
		"ypos"					"140"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias6"
		"navDown"				"BtnAntialias8"
		"labelText"				"_antialias7"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias7"
		"OnlyActiveUser"		"1"
	}
	
	"BtnAntialias8"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias8"
		"xpos"					"0"
		"ypos"					"160"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias7"
		"navDown"				"BtnAntialias9"
		"labelText"				"_antialias8"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias8"
		"OnlyActiveUser"		"1"
	}
	
	"BtnAntialias9"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnAntialias9"
		"xpos"					"0"
		"ypos"					"180"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnAntialias8"
		"navDown"				"BtnAntialias0"
		"labelText"				"_antialias9"
		"tooltiptext"			"#GameUI_Antialiasing_Mode"
		"disabled_tooltiptext"	"#GameUI_Antialiasing_Mode"
		"style"					"FlyoutMenuButton"
		"command"				"_antialias9"
		"OnlyActiveUser"		"1"
	}
}
