"Resource/UI/DropDownSpraypaint.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"156"
		"tall"					"325"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}
	
	"BtnSpraypaint0"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint0"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint@"
		"navDown"				"BtnSpraypaint1"
		"labelText"				"_spraypaint0"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint0"
		"OnlyActiveUser"		"1"
	}

	"BtnSpraypaint1"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint1"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint0"
		"navDown"				"BtnSpraypaint2"
		"labelText"				"_spraypaint1"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint1"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint2"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint2"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint1"
		"navDown"				"BtnSpraypaint3"
		"labelText"				"_spraypaint2"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint2"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint3"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint3"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint2"
		"navDown"				"BtnSpraypaint4"
		"labelText"				"_spraypaint3"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint3"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint4"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint4"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint3"
		"navDown"				"BtnSpraypaint5"
		"labelText"				"_spraypaint4"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint4"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint5"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint5"
		"xpos"					"0"
		"ypos"					"100"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint4"
		"navDown"				"BtnSpraypaint6"
		"labelText"				"_spraypaint5"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint5"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint6"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint6"
		"xpos"					"0"
		"ypos"					"120"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint5"
		"navDown"				"BtnSpraypaint7"
		"labelText"				"_spraypaint6"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint6"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint7"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint7"
		"xpos"					"0"
		"ypos"					"140"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint6"
		"navDown"				"BtnSpraypaint8"
		"labelText"				"_spraypaint7"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint7"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint8"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint8"
		"xpos"					"0"
		"ypos"					"160"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint7"
		"navDown"				"BtnSpraypaint9"
		"labelText"				"_spraypaint8"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint8"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint9"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint9"
		"xpos"					"0"
		"ypos"					"180"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint8"
		"navDown"				"BtnSpraypaint:"
		"labelText"				"_spraypaint9"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint9"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint:"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint:"
		"xpos"					"0"
		"ypos"					"200"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint9"
		"navDown"				"BtnSpraypaint;"
		"labelText"				"_spraypaint:"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint:"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint;"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint;"
		"xpos"					"0"
		"ypos"					"220"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint:"
		"navDown"				"BtnSpraypaint<"
		"labelText"				"_spraypaint;"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint;"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint<"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint<"
		"xpos"					"0"
		"ypos"					"240"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint;"
		"navDown"				"BtnSpraypaint="
		"labelText"				"_spraypaint<"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint<"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint="
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint="
		"xpos"					"0"
		"ypos"					"260"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint<"
		"navDown"				"BtnSpraypaint>"
		"labelText"				"_spraypaint="
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint="
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint>"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint>"
		"xpos"					"0"
		"ypos"					"280"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint="
		"navDown"				"BtnSpraypaint?"
		"labelText"				"_spraypaint>"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint>"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint?"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint?"
		"xpos"					"0"
		"ypos"					"300"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint>"
		"navDown"				"BtnSpraypaint@"
		"labelText"				"_spraypaint?"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint?"
		"OnlyActiveUser"		"1"
	}
	
	"BtnSpraypaint@"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnSpraypaint@"
		"xpos"					"0"
		"ypos"					"320"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnSpraypaint?"
		"navDown"				"BtnSpraypaint0"
		"labelText"				"_spraypaint@"
		"tooltiptext"			"#GameUI_SpraypaintServerNote"
		"disabled_tooltiptext"	"#GameUI_SpraypaintServerNote"
		"style"					"FlyoutMenuButton"
		"command"				"_spraypaint@"
		"OnlyActiveUser"		"1"
	}
}
