"Resource/UI/DropDownResolution.res"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"156"
		"tall"					"305"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}
	
	"BtnRes0"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes0"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes>"
		"navDown"				"BtnRes1"
		"labelText"				"_res0"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res0"
		"OnlyActiveUser"		"1"
	}

	"BtnRes1"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes1"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes0"
		"navDown"				"BtnRes2"
		"labelText"				"_res1"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res1"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes2"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes2"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes1"
		"navDown"				"BtnRes3"
		"labelText"				"_res2"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res2"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes3"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes3"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes2"
		"navDown"				"BtnRes4"
		"labelText"				"_res3"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res3"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes4"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes4"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes3"
		"navDown"				"BtnRes5"
		"labelText"				"_res4"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res4"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes5"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes5"
		"xpos"					"0"
		"ypos"					"100"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes4"
		"navDown"				"BtnRes6"
		"labelText"				"_res5"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res5"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes6"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes6"
		"xpos"					"0"
		"ypos"					"120"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes5"
		"navDown"				"BtnRes7"
		"labelText"				"_res6"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res6"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes7"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes7"
		"xpos"					"0"
		"ypos"					"140"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes6"
		"navDown"				"BtnRes8"
		"labelText"				"_res7"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res7"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes8"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes8"
		"xpos"					"0"
		"ypos"					"160"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes7"
		"navDown"				"BtnRes9"
		"labelText"				"_res8"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res8"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes9"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes9"
		"xpos"					"0"
		"ypos"					"180"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes8"
		"navDown"				"BtnRes:"
		"labelText"				"_res9"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res9"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes:"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes:"
		"xpos"					"0"
		"ypos"					"200"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes9"
		"navDown"				"BtnRes;"
		"labelText"				"_res:"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res:"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes;"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes;"
		"xpos"					"0"
		"ypos"					"220"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes:"
		"navDown"				"BtnRes<"
		"labelText"				"_res;"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res;"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes<"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes<"
		"xpos"					"0"
		"ypos"					"240"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes;"
		"navDown"				"BtnRes="
		"labelText"				"_res<"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res<"
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes="
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes="
		"xpos"					"0"
		"ypos"					"260"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes<"
		"navDown"				"BtnRes>"
		"labelText"				"_res="
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res="
		"OnlyActiveUser"		"1"
	}
	
	"BtnRes>"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnRes>"
		"xpos"					"0"
		"ypos"					"280"
		"wide"					"150"
		"tall"					"20"
		"autoResize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnRes="
		"navDown"				"BtnRes0"
		"labelText"				"_res>"
		"tooltiptext"			"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"disabled_tooltiptext"	"#L4D360UI_VideoOptions_Tooltip_Resolution"
		"style"					"FlyoutMenuButton"
		"command"				"_res>"
		"OnlyActiveUser"		"1"
	}
}
