"Languageource/UI/DropDownLanguage.language"
{
	"PnlBackground"
	{
		"ControlName"			"Panel"
		"fieldName"				"PnlBackground"
		"xpos"					"0"
		"ypos"					"0"
		"zpos"					"-1"
		"wide"					"156"
		"tall"					"305"
		"visible"				"1"
		"enabled"				"1"
		"paintbackground"		"1"
		"paintborder"			"1"
	}
	
	"BtnLanguage0"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage0"
		"xpos"					"0"
		"ypos"					"0"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage>"
		"navDown"				"BtnLanguage1"
		"labelText"				"_language0"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language0"
		"OnlyActiveUser"		"1"
	}

	"BtnLanguage1"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage1"
		"xpos"					"0"
		"ypos"					"20"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage0"
		"navDown"				"BtnLanguage2"
		"labelText"				"_language1"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language1"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage2"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage2"
		"xpos"					"0"
		"ypos"					"40"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage1"
		"navDown"				"BtnLanguage3"
		"labelText"				"_language2"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language2"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage3"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage3"
		"xpos"					"0"
		"ypos"					"60"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage2"
		"navDown"				"BtnLanguage4"
		"labelText"				"_language3"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language3"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage4"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage4"
		"xpos"					"0"
		"ypos"					"80"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage3"
		"navDown"				"BtnLanguage5"
		"labelText"				"_language4"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language4"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage5"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage5"
		"xpos"					"0"
		"ypos"					"100"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage4"
		"navDown"				"BtnLanguage6"
		"labelText"				"_language5"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language5"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage6"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage6"
		"xpos"					"0"
		"ypos"					"120"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage5"
		"navDown"				"BtnLanguage7"
		"labelText"				"_language6"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language6"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage7"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage7"
		"xpos"					"0"
		"ypos"					"140"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage6"
		"navDown"				"BtnLanguage8"
		"labelText"				"_language7"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language7"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage8"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage8"
		"xpos"					"0"
		"ypos"					"160"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage7"
		"navDown"				"BtnLanguage9"
		"labelText"				"_language8"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language8"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage9"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage9"
		"xpos"					"0"
		"ypos"					"180"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage8"
		"navDown"				"BtnLanguage:"
		"labelText"				"_language9"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language9"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage:"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage:"
		"xpos"					"0"
		"ypos"					"200"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage9"
		"navDown"				"BtnLanguage;"
		"labelText"				"_language:"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language:"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage;"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage;"
		"xpos"					"0"
		"ypos"					"220"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage:"
		"navDown"				"BtnLanguage<"
		"labelText"				"_language;"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language;"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage<"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage<"
		"xpos"					"0"
		"ypos"					"240"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage;"
		"navDown"				"BtnLanguage="
		"labelText"				"_language<"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language<"
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage="
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage="
		"xpos"					"0"
		"ypos"					"260"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage<"
		"navDown"				"BtnLanguage>"
		"labelText"				"_language="
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language="
		"OnlyActiveUser"		"1"
	}
	
	"BtnLanguage>"
	{
		"ControlName"			"L4D360HybridButton"
		"fieldName"				"BtnLanguage>"
		"xpos"					"0"
		"ypos"					"280"
		"wide"					"150"
		"tall"					"20"
		"autoLanguageize"			"1"
		"pinCorner"				"0"
		"visible"				"1"
		"enabled"				"1"
		"tabPosition"			"0"
		"wrap"					"1"
		"navUp"					"BtnLanguage="
		"navDown"				"BtnLanguage0"
		"labelText"				"_language>"
		"tooltiptext"			"#L4D360UI_AudioOptions_Tooltip_Language"
		"disabled_tooltiptext"	"#L4D360UI_AudioOptions_Tooltip_Language"
		"style"					"FlyoutMenuButton"
		"command"				"_language>"
		"OnlyActiveUser"		"1"
	}
}
