"use strict";

var watchEventLiveExample_01 = "";
var watchEventLiveExample_02 = "";
var watchEventLiveExample_03 = "";
var teamExample = "";

var ADD_DEBUG_EVENT = "0";

          
                                                    
                                  
  

                             
                              
                   
                     
             
                                                                                                                
             
                                                                                                                
                                                       
                                                     
                  
                             
                   
                                                                    
                   
       
                            
                             
                          
                       
                                                                                                                    
                       
                                                                                                                    
                  
           
                              
                           
                                                                                                          
                      
            
          
                       
                                                                                                                        
        
      
            
       
                        
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                    
                 
                                                                                                                    
        
       
                              
                 
                                                                                                                    
        
       
                     
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                          
                 
                                                                                                                    
        
       
                            
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                                
                 
                                                                                                                    
        
       
                      
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
      
                      
                              
    
                              
                   
                     
                      
             
                                                                                                                
             
                                                                                                                
                                                       
                                                     
                  
                             
                   
                                                                    
                   
       
                            
                                    
                                  
                       
                                                                                                                    
                       
                                                                                                                    
                    
                       
                                                                                                                                       
        
       
                            
                             
                          
                       
                                                                                                                    
                       
                                                                                                                    
                  
           
                              
                           
                                                                                                         
                      
            
          
                       
                                                                                                                        
        
      
            
       
                        
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                    
                 
                                                                                                                    
        
       
                              
                 
                                                                                                                    
        
       
                     
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                          
                 
                                                                                                                    
        
       
                            
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                                
                 
                                                                                                                    
        
       
                      
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
      
                      
                              
    
                              
                   
                     
                      
             
                                                                                                                
             
                                                                                                                
                                                       
                                                     
                  
                             
                   
                                                                    
                   
       
                            
                             
                                      
                       
                                                                                                                    
                       
                                                                                                                    
                  
           
                            
                           
                                                                                                         
                      
            
           
                             
                           
                                                                                                      
                      
            
           
                             
                           
                                                                                                     
                      
            
           
                              
                           
                           
                                                                                                
                      
            
           
                              
                           
                           
                                                                                                
                      
                          
            
           
                              
                                
                           
                                                                     
                      
            
           
                              
                           
                                                                                                         
                      
            
           
                              
                           
                                                                                                   
                      
            
           
                              
                            
                           
                                                                     
                      
            
           
                              
                           
                                                                                                     
                      
            
           
                              
                           
                                                                                                          
                      
            
           
                              
                           
                                                                                                     
                      
                          
            
           
                              
                           
                                                                                                          
                      
            
           
                              
                           
                                                                                                    
                      
                          
            
           
                              
                           
                                                                                                          
                      
            
           
                              
                           
                           
                                                                                                   
                      
                           
            
           
                              
                           
                                                                                                     
                      
                          
            
           
                              
                           
                                                                                                          
                      
                          
            
           
                              
                            
                           
                                                                     
                      
            
           
                              
                           
                                                                                                         
                         
            
           
                              
                           
                                                                                                      
                      
            
           
                              
                           
                                                                                                        
                      
            
           
                              
                           
                                                                                                     
                      
                          
            
           
                              
                         
                                                                         
                      
                          
            
           
                              
                           
                                                                                                     
                      
            
          
                       
                                                                                                                                    
        
       
                            
                               
                                
                       
                                                                                                                    
                       
                                                                                                                    
                  
           
                              
                           
                                                                                                      
                      
            
          
                       
                                                                                                                                
        
       
                            
                                    
                                  
                       
                                                                                                                    
                       
                                                                                                                    
                    
                       
                                                                                                         
        
       
                            
                             
                          
                       
                                                                                                                    
                       
                                                                                                                    
                  
           
                              
                           
                                                                                                         
                      
            
          
                       
                                                                                                                        
        
      
            
       
                        
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                    
                 
                                                                                                                    
        
       
                              
                 
                                                                                                                    
        
       
                     
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                          
                 
                                                                                                                    
        
       
                            
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                       
                 
                                                                                                                    
        
       
                                
                 
                                                                                                                    
        
       
                      
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
       
                         
                 
                                                                                                                    
        
      
                      
                              
    

                 
                     
                                                              
                                                    
             
       
                          
                                      
                     
                                                                                      
                            
                   
                                                                                        
                                                             
          
                
                                                              
        
       
                            
                                    
                     
                                                                                      
                            
                   
                                                                                        
                                                             
          
                
                                                                
        
       
                           
                                    
                     
                                                                                      
                            
                   
                                                                                        
                                                            
          
                
                                                               
        
       
                           
                                   
                     
                                                                                      
                            
                   
                                                                                        
                                                           
          
                
                                                               
        
       
                           
                              
                     
                                                                                      
                            
                   
                                                                                         
                                                      
          
                
                                                               
        
      
    
 
          
