class CMapInfo : public CPointEntity
{
	int32 m_iBuyingStatus;
	float32 m_flBombRadius;
	int32 m_iPetPopulation;
	bool m_bUseNormalSpawnsForDM;
	bool m_bDisableAutoGeneratedDMSpawns;
	float32 m_flBotMaxVisionDistance;
	int32 m_iHostageCount;
	bool m_bFadePlayerVisibilityFarZ;
	bool m_bRainTraceToSkyEnabled;
	float32 m_flEnvRainStrength;
	float32 m_flEnvPuddleRippleStrength;
	float32 m_flEnvPuddleRippleDirection;
	float32 m_flEnvWetnessCoverage;
	float32 m_flEnvWetnessDryingAmount;
};
